<?php

namespace TADSNexcon\Webcar\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT b, l FROM TADSNexconWebcarCoreBundle:Brand b LEFT JOIN b.logo l ORDER BY b.name ASC'
            )
            ->getResult();
    }
    
}
