<?php

namespace TADSNexcon\Webcar\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConcessionaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcessionaryRepository extends EntityRepository
{
    
    public function findByBrand($id){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c, b FROM TADSNexconWebcarCoreBundle:Concessionary c LEFT JOIN c.brands b WHERE b.id = :brandId'
            )
            ->setParameter('brandId', $id)
            ->getResult();
    }
    
}
