<?php

namespace TADSNexcon\Webcar\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends EntityRepository
{
    
    //TODO
    public function findComplete($id){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m, c,  FROM TADSNexconWebcarCoreBundle:Model v JOIN v.modelColors c, JOIN WHERE v.brand = :brand  ORDER BY v.name ASC '
            )
            ->setParameter('brand', $brand)
            ->getResult();
    }
    
}
