<?php

namespace TADSNexcon\Webcar\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends EntityRepository
{
    
    //TODO
    public function findComplete($modelId){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m, mc, k, a, i, c FROM TADSNexconWebcarCoreBundle:Model m LEFT JOIN m.modelColors mc LEFT JOIN mc.color c LEFT JOIN  m.kits k LEFT JOIN m.acessories a LEFT JOIN m.mainImage i WHERE m.id = :modelId'
            )
            ->setParameter('modelId', $modelId)
            ->getOneOrNullResult();
    }
    
}
