<?php

namespace TADSNexcon\Webcar\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use TADSNexcon\Webcar\CoreBundle\Entity\Brand;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRepository extends EntityRepository
{
    
    public function findVehiclesByBrand(\Brand $brand){
        return $this->findVehiclesByBrandId($brand->getId());
    }
    
    //TODO
    public function findVehiclesByBrandId($brand){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM TADSNexconWebcarCoreBundle:Vehicle v WHERE v.brand = :brand  ORDER BY v.name ASC '
            )
            ->setParameter('brand', $brand)
            ->getResult();
    }
}
